# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '3'
services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - web

  memcached:
    restart: unless-stopped
    image: memcached:1.5
    networks:
      - web

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    networks:
      - web

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    networks:
      - web
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    #ports:
    #  - '5432:5432'

  web:
    restart: unless-stopped
    build: .
    env_file: .env
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - web
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    ports:
      - '127.0.0.1:9000:9000'

  cron:
    restart: unless-stopped
    build: .
    command: run cron
    env_file: .env
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - web
    volumes:
      - ./data/sentry:/var/lib/sentry/files
      
  worker:
    restart: unless-stopped
    build: .
    command: run worker
    env_file: .env
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - web
    volumes:
      - ./data/sentry:/var/lib/sentry/files

networks:
  web: